export const counterChangeTypes = {
  INCREMENT_COUNT: "INCREMENT_COUNT",
  DECREMENT_COUNT: "DECREMENT_COUNT",
  INCREMENT_COUNT_2: "INCREMENT_COUNT_2",
  DECREMENT_COUNT_2: "DECREMENT_COUNT_2",
  SET_F1_DRIVERS: "SET_F1_DRIVERS",
};
